# Generated by Django 4.0.4 on 2022-07-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='last_updated',
            new_name='date',
        ),
    ]
